### ISSUE TITLE
"Don't demand notice" and "end of work notice"

### ISSUE THREAD

**Issue by eyalroz** [YoavHaifa/WorkersRightsComputer#29]
When a user sets "don't demand notice" to true (enabled), the date field for "End of work notice" should be grayed-out (and possibly cleared).

**Comment by YoavHaifa** [comment]
ישנם מקרים שבהם יש משמעות לידיעה של מועד ההודעה המוקדמת למרות שאיננו מבקשים חלף הודעה מוקדמת.  לפיכך ברצוני לשמור על אפשרות למלא את הנתון הזה בתכנה.

**Comment by eyalroz** [comment]
Fair enough, closing this issue.
